# Generated by Django 3.2.8 on 2021-10-28 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voluntarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('funcao', models.CharField(max_length=30)),
                ('numero_de_id', models.IntegerField()),
            ],
        ),
    ]
