# Generated by Django 3.2.8 on 2021-11-23 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voluntarios',
            name='numero_de_id',
        ),
        migrations.AddField(
            model_name='voluntarios',
            name='curriculo',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='voluntarios',
            name='horas_contribuidas',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voluntarios',
            name='horas_semanais',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voluntarios',
            name='sobrenome',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
