# Generated by Django 3.2.8 on 2021-11-23 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0002_auto_20211123_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='voluntarios',
            name='bairro',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voluntarios',
            name='cpf',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voluntarios',
            name='email',
            field=models.EmailField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voluntarios',
            name='telefone',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
