# Generated by Django 3.2.8 on 2021-11-23 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0003_auto_20211123_0315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voluntarios',
            name='curriculo',
        ),
    ]
