# Generated by Django 3.2.8 on 2021-11-23 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0004_remove_voluntarios_curriculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voluntarios',
            name='horas_contribuidas',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='voluntarios',
            name='horas_semanais',
            field=models.IntegerField(),
        ),
    ]
